train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ['Winding_Z']

roboflow:
  workspace: quang-truong-huynh
  project: pin-3dc
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/quang-truong-huynh/pin-3dc/dataset/1